// mutation-types.js

export const SET_PLAYLIST_STATE = 'SET_PLAYLIST_STATE'

export const SET_CURRENTINDEX_STATE = 'SET_CURRENTINDEX_STATE'

export const SET_CURRENTSONG_STATE = 'SET_CURRENTSONG_STATE'

export const SET_CURRENTPLAYFLAG_STATE = 'SET_CURRENTPLAYFLAG_STATE'
